# Navigation Links

main:
  - name: Home
    url: '/#about'
    weight: 10
  - name: Research
    url: '/#research'
    weight: 20
  - name: CV
    url: '/files/cv.pdf'
    weight: 30
  - name: Contact
    url: '/#contact'
    weight: 40
